version: "3"
services:
  tw-mariadb:
    image: mariadb:latest
    container_name: tw-mariadb
    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tw
    volumes:
      - ../tw-db-data:/var/lib/mysql
    networks:
      - tw-net 
  tw-redis:
    image: "redis:alpine"
    container_name: tw-redis
    restart: always
    expose:
      - "6379"
    command: redis-server
    networks:
      - tw-net
  tw-backend:
    image: tycorp/trading-waza-spring-app:latest
    container_name: tw-backend
    restart: always
    ports:
      - "8080:8080"
    networks:
      - tw-net  
    depends_on:
      - tw-mariadb
      - tw-redis
  tw-backend-smsl-mgm:
    image: tycorp/trading-waza-smsl-mgm-app:latest
    container_name: tw-backend-smsl-mgm
    restart: always
    expose:
      - "3000"
    networks:
      - tw-net
      
networks:
  tw-net:
    name: tw-net

