version: "3"
services:
  tb-mariadb:
    image: mariadb:latest
    container_name: tb-mariadb
    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tb
    volumes:
      - ../tbdbdata:/var/lib/mysql
    networks:
      - tb-net 
  tb-redis:
    image: "redis:alpine"
    container_name: tb-redis
    restart: always
    expose:
      - "6379"
    command: redis-server
    networks:
      - tb-net
  tb-portal:
    image: tycorp/tb-portal-spring-app:latest
    container_name: tb-portal
    restart: always
    ports:
      - "8080:8080"
    networks:
      - tb-net  
    depends_on:
      - tb-mariadb
      - tb-redis
networks:
  tb-net:
    name: tb-net

